FROM scratch AS source

ADD elm.json /work/elm.json
ADD src /work/src
ADD review /work/review


FROM ghcr.io/asssaf/elm:master AS validate

COPY --from=source /work /work

WORKDIR /work

RUN elm-format --validate ./src

RUN elm-review


FROM validate AS optimize

WORKDIR /work
RUN elm make --optimize --output=main.js /work/src/Main.elm


FROM scratch AS output

COPY --from=optimize /work/main.js /main.js
