FROM scratch AS source

ADD elm.json /work/elm.json
ADD src /work/src


FROM ghcr.io/asssaf/elm:master AS validate

COPY --from=source /work /work
RUN elm-format --validate /work/src

RUN elm-review --template jfmengels/elm-review-unused/example --elmjson /work/elm.json /work

FROM validate AS optimize

WORKDIR /work
RUN elm make --optimize --output=main.js /work/src/Main.elm


FROM scratch AS output

COPY --from=optimize /work/main.js /main.js
